### ISSUE TITLE
Feature Request : Setting both top/bottom properties and left/right properties should resize the item

### ISSUE THREAD

**Issue by ludovic-loridan** [AntonStrand/dynamic-reposition#1]
Like in CSS, that would be great because it would allow to create "stretchable" items.
Great plugin ! :+1:

**Comment by AntonStrand** [comment]
Glad to hear you like it and a it is great suggestion. I got quite a lot to do right now, but I'll add it asap. 
In the meantime perhaps my other plugin might work [Sketch Resize](https://github.com/AntonStrand/Sketch-Resize)

**Comment by AntonStrand** [comment]
It seems to work as it supposed to but I haven't had the time to really test it yet. Please let me know if you find anything. Thanks for the suggestion by the way!
